### PR TITLE
isabelle log: show timing info

### PR DESCRIPTION
**Pull request by lsf37**
Add the following options to `isabelle log`:

* `-c` show command timings
* `-s` sort timing output by elapsed time
* `-t` show theory timings

### CODE REVIEW

**Comment by lsf37** [comment]
Sample output of `isabelle log -t -s Word_Lib`:

```
Theory timing Word_Lib.More_Misc: 0.039s elapsed time, 0.225s cpu time, 0.000s GC time
Theory timing Word_Lib.Syntax_Bundles: 0.039s elapsed time, 0.270s cpu time, 0.000s GC time
Theory timing Word_Lib.Word_Names: 0.039s elapsed time, 0.283s cpu time, 0.000s GC time
Theory timing Word_Lib.Hex_Words: 0.044s elapsed time, 0.371s cpu time, 0.000s GC time
Theory timing HOL-Eisbach.Eisbach_Tools: 0.053s elapsed time, 0.422s cpu time, 0.000s GC time
Theory timing Word_Lib.Machine_Word_64_Basics: 0.059s elapsed time, 0.161s cpu time, 0.000s GC time
Theory timing Word_Lib.Strict_part_mono: 0.060s elapsed time, 0.452s cpu time, 0.000s GC time
Theory timing Word_Lib.Type_Syntax: 0.072s elapsed time, 0.452s cpu time, 0.000s GC time
Theory timing Word_Lib.Machine_Word_64: 0.077s elapsed time, 0.291s cpu time, 0.000s GC time
Theory timing Word_Lib.Machine_Word_32_Basics: 0.085s elapsed time, 0.623s cpu time, 0.000s GC time
Theory timing Word_Lib.More_Sublist: 0.089s elapsed time, 0.481s cpu time, 0.000s GC time
Theory timing Word_Lib.More_Arithmetic: 0.100s elapsed time, 0.459s cpu time, 0.000s GC time
Theory timing Word_Lib.Next_and_Prev: 0.100s elapsed time, 0.886s cpu time, 0.000s GC time
Theory timing Word_Lib.Rsplit: 0.103s elapsed time, 0.761s cpu time, 0.000s GC time
Theory timing Word_Lib.Norm_Words: 0.106s elapsed time, 0.791s cpu time, 0.000s GC time
Theory timing Word_Lib.Even_More_List: 0.112s elapsed time, 0.621s cpu time, 0.000s GC time
Theory timing Word_Lib.Machine_Word_32: 0.112s elapsed time, 0.919s cpu time, 0.110s GC time
Theory timing Word_Lib.Word_Syntax: 0.116s elapsed time, 0.770s cpu time, 0.105s GC time
Theory timing HOL-Library.Prefix_Order: 0.124s elapsed time, 0.703s cpu time, 0.000s GC time
Theory timing Word_Lib.Singleton_Bit_Shifts: 0.161s elapsed time, 1.321s cpu time, 0.000s GC time
Theory timing Word_Lib.Ancient_Numeral: 0.186s elapsed time, 1.085s cpu time, 0.195s GC time
Theory timing Word_Lib.Legacy_Aliases: 0.201s elapsed time, 1.441s cpu time, 0.000s GC time
Theory timing Word_Lib.Signed_Words: 0.207s elapsed time, 1.421s cpu time, 0.105s GC time
Theory timing Word_Lib.Most_significant_bit: 0.241s elapsed time, 1.914s cpu time, 0.117s GC time
Theory timing Word_Lib.Word_16: 0.249s elapsed time, 1.741s cpu time, 0.000s GC time
Theory timing Word_Lib.More_Divides: 0.278s elapsed time, 1.881s cpu time, 0.105s GC time
Theory timing Word_Lib.WordSetup: 0.288s elapsed time, 2.266s cpu time, 0.089s GC time
Theory timing HOL-Library.Signed_Division: 0.303s elapsed time, 1.566s cpu time, 0.000s GC time
Theory timing Word_Lib.Word_Lemmas_32_Internal: 0.337s elapsed time, 2.724s cpu time, 0.090s GC time
Theory timing Word_Lib.Typedef_Morphisms: 0.355s elapsed time, 2.750s cpu time, 0.116s GC time
Theory timing Word_Lib.Bitwise: 0.397s elapsed time, 3.108s cpu time, 0.182s GC time
Theory timing Word_Lib.Word_64: 0.559s elapsed time, 0.752s cpu time, 0.076s GC time
Theory timing Word_Lib.Distinct_Prop: 0.584s elapsed time, 3.767s cpu time, 0.274s GC time
Theory timing HOL-Library.Type_Length: 0.608s elapsed time, 1.514s cpu time, 0.000s GC time
Theory timing Word_Lib.Word_Lemmas_Prefix: 0.608s elapsed time, 4.953s cpu time, 0.215s GC time
Theory timing Word_Lib.Signed_Division_Word: 0.668s elapsed time, 5.037s cpu time, 0.215s GC time
Theory timing Word_Lib.Aligned: 0.687s elapsed time, 5.403s cpu time, 0.199s GC time
Theory timing Word_Lib.Enumeration_Word: 0.752s elapsed time, 5.294s cpu time, 0.219s GC time
Theory timing Word_Lib.Many_More: 0.754s elapsed time, 5.193s cpu time, 0.116s GC time
Theory timing Word_Lib.Guide: 0.771s elapsed time, 1.365s cpu time, 0.040s GC time
Theory timing Word_Lib.Generic_set_bit: 0.892s elapsed time, 7.351s cpu time, 0.183s GC time
Theory timing Word_Lib.Bitwise_Signed: 0.907s elapsed time, 6.021s cpu time, 4.129s GC time
Theory timing Word_Lib.Word_Lemmas_Internal: 0.985s elapsed time, 8.368s cpu time, 0.202s GC time
Theory timing Word_Lib.Least_significant_bit: 1.015s elapsed time, 7.017s cpu time, 0.376s GC time
Theory timing Word_Lib.Word_32: 1.035s elapsed time, 8.829s cpu time, 0.202s GC time
Theory timing Word_Lib.Enumeration: 1.060s elapsed time, 5.733s cpu time, 0.150s GC time
Theory timing HOL-Library.Cardinality: 1.090s elapsed time, 7.143s cpu time, 0.218s GC time
Theory timing HOL-Library.Numeral_Type: 1.218s elapsed time, 6.192s cpu time, 0.271s GC time
Theory timing HOL-Library.Phantom_Type: 1.265s elapsed time, 7.139s cpu time, 0.348s GC time
Theory timing Word_Lib.Word_8: 1.376s elapsed time, 10.213s cpu time, 0.409s GC time
Theory timing HOL-Eisbach.Eisbach: 1.399s elapsed time, 8.107s cpu time, 0.348s GC time
Theory timing Word_Lib.Examples: 1.638s elapsed time, 8.186s cpu time, 4.396s GC time
Theory timing Word_Lib.Bit_Comprehension: 1.705s elapsed time, 12.741s cpu time, 0.389s GC time
Theory timing Word_Lib.Word_Lib_Sumo: 1.735s elapsed time, 13.772s cpu time, 0.440s GC time
Theory timing Word_Lib.More_Word_Operations: 1.745s elapsed time, 12.547s cpu time, 4.478s GC time
Theory timing Word_Lib.Bit_Shifts_Infix_Syntax: 1.947s elapsed time, 13.438s cpu time, 0.593s GC time
Theory timing Word_Lib.Word_EqI: 2.237s elapsed time, 18.389s cpu time, 0.518s GC time
Theory timing Word_Lib.More_Word: 2.239s elapsed time, 15.801s cpu time, 0.454s GC time
Theory timing Word_Lib.Word_Lemmas: 2.277s elapsed time, 16.390s cpu time, 0.564s GC time
Theory timing HOL-Library.Sublist: 2.842s elapsed time, 17.528s cpu time, 0.689s GC time
Theory timing Word_Lib.Reversed_Bit_Lists: 2.888s elapsed time, 21.796s cpu time, 0.871s GC time
Theory timing Word_Lib.Bits_Int: 3.397s elapsed time, 25.693s cpu time, 0.763s GC time
Theory timing HOL-Library.Word: 7.820s elapsed time, 31.034s cpu time, 1.100s GC time
```

**Comment by lsf37** [comment]
We could leave out the `Command timing` and `Theory timing` prefixes if those are annoying, but if you supply both at the command line you get both as output. Still in separate sections, but I found it useful to immediately see what I was looking at while I was scrolling through things.

**Comment by Xaphiosis** [comment]
I think this looks useful and the Scala looks ok (not that I'm any expert). Some thoughts/questions:
* If the `Theory timing` and `Command timing` won't interlace, would it improve readability to print the title of the section once, and then the subsequent timings rather than repeat it on every line?
* For command timing, what are your thoughts on the `command location time` ordering? Did you consider `command time location` as well? 
* For upstream inclusion, I think keeping the offset notation will be what they want, but I don't know how to map those offsets to locations in a file easily and would probably find line numbers easier to jump to.
* For upstream inclusion, I can see people getting a bit confused with the interaction between `-c` `-t` and say `-v` which claims to print everything, and that either of the options suppresses normal output. Then again, commands in Isabelle tend to be so confusing already... (e.g. what does `-m MARGIN` do?)

**Review by Xaphiosis — APPROVED** [review]

**Comment by lsf37** [comment]
> * If the `Theory timing` and `Command timing` won't interlace, would it improve readability to print the title of the section once, and then the subsequent timings rather than repeat it on every line?

I'll give that a go.

> * For command timing, what are your thoughts on the `command location time` ordering? Did you consider `command time location` as well?

I've considered it, but not tried it. It feels a bit strange to just see lots of "apply" with numbers without an indication on a least which file the command is from.

> * For upstream inclusion, I think keeping the offset notation will be what they want, but I don't know how to map those offsets to locations in a file easily and would probably find line numbers easier to jump to.

I would too, but there is no way to get that information, we only have the offset. The file that is mentioned in the database might not even exist any more, so trying to look it up and counting lines during printing only makes sense when you know you've just built the session. I think we have to leave this translation external to the `log` tool.


> * For upstream inclusion, I can see people getting a bit confused with the interaction between `-c` `-t` and say `-v` which claims to print everything, and that either of the options suppresses normal output. Then again, commands in Isabelle tend to be so confusing already... (e.g. what does `-m MARGIN` do?)

Excellent point, `-v` should print everything. I excluded the theory output when the others are on, because it takes forever and is usually not useful, but it should definitely be there when `-v` is given.

(the margin option is for printing the theory output, it's probably pretty-printing terms there)

**Comment by lsf37** [comment]
> > * For command timing, what are your thoughts on the `command location time` ordering? Did you consider `command time location` as well?
> 
> I've considered it, but not tried it. It feels a bit strange to just see lots of "apply" with numbers without an indication on a least which file the command is from.

You had the right instinct, I tried it out and it looks better with the "command", "time", "location" order.

**Review by michaelmcinerney — APPROVED** [review]
I only glanced at the Scala, but from a user perspective, this works really nicely, especially with the ability to sort the output

**Pull request merged**
